Repository Team-Archive/AboutTime-iOS, pull requests merged in 2024-06, with the labels that each got.

#23 makeTargetProject.sh 구현
  Project/Tools/makeTargetProject.sh
Labels: enhancement

#22 APIHub패키지 제거 및 ReadMe.md 수정
  Project/Projects/APIHub/Project.swift
  Project/Projects/APIHub/Resources/Dummy.png
  Project/Projects/APIHub/SampleApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Project/Projects/APIHub/SampleApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/Projects/APIHub/SampleApp/Resources/Assets.xcassets/Contents.json
  Project/Projects/APIHub/SampleApp/Sources/ContentView.swift
  Project/Projects/APIHub/SampleApp/Sources/SampleApp.swift
  Project/Projects/APIHub/Sources/AppstoreAPI.swift
  Project/Projects/APIHub/TestHost/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Project/Projects/APIHub/TestHost/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/Projects/APIHub/TestHost/Resources/Assets.xcassets/Contents.json
  Project/Projects/APIHub/TestHost/Sources/HostApp.swift
  Project/Projects/APIHub/Tests/Extension/UIntExtensionTests.swift
  Project/Projects/Data/Project.swift
  Project/Workspace.swift
  README.md
Labels: documentation

#21 Feature/OAuth
  Project/.gitignore
  Project/Projects/App/Project.swift
  Project/Projects/ArchiveFoundation/Project.swift
  Project/Projects/ArchiveFoundation/Resources/country.json
  Project/Projects/ArchiveFoundation/Sources/Model/ArchiveError.swift
  Project/Projects/ArchiveFoundation/Sources/Model/Country.swift
  Project/Projects/ArchiveFoundation/Sources/Model/OAuthProvider.swift
  Project/Projects/ArchiveFoundation/Sources/Protocol/OAuth.swift
  Project/Projects/ArchiveFoundation/Tests/Model/CountryTests.swift
  Project/Projects/Feature/SignUp/Project.swift
  Project/Projects/Feature/SignUp/Resources/Dummy.png
  Project/Projects/Feature/SignUp/SampleApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Project/Projects/Feature/SignUp/SampleApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/Projects/Feature/SignUp/SampleApp/Resources/Assets.xcassets/Contents.json
  Project/Projects/Feature/SignUp/SampleApp/Sources/SampleApp.swift
  Project/Projects/Feature/SignUp/Sources/Internal/1. SetProfile/SignUpSetProfileView.swift
  Project/Projects/Feature/SignUp/Sources/Internal/2. SetCity/SignUpSetCityView.swift
  Project/Projects/Feature/SignUp/Sources/Internal/3. SetActivityTime/SetActivityTIme.swift
  Project/Projects/Feature/SignUp/Sources/Internal/SubComponents/SignUpFakeNavigationView.swift
  Project/Projects/Feature/SignUp/Sources/Internal/SubComponents/SignUpProgressView.swift
  Project/Projects/Feature/SignUp/Sources/Public/SignUpReducer.swift
  Project/Projects/Feature/SignUp/Sources/Public/SignUpView.swift
  Project/Projects/Feature/SignUp/TestHost/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Project/Projects/Feature/SignUp/TestHost/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/Projects/Feature/SignUp/TestHost/Resources/Assets.xcassets/Contents.json
  Project/Projects/Feature/SignUp/TestHost/Sources/HostApp.swift
  Project/Projects/Feature/SignUp/Tests/Extension/UIntExtensionTests.swift
  Project/Projects/OAuth/Apple/Project.swift
  Project/Projects/OAuth/Apple/Resources/Dummy.png
  Project/Projects/OAuth/Apple/SampleApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Project/Projects/OAuth/Apple/SampleApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/Projects/OAuth/Apple/SampleApp/Resources/Assets.xcassets/Contents.json
  Project/Projects/OAuth/Apple/SampleApp/Sources/SampleApp.swift
  Project/Projects/OAuth/Apple/Sources/Public/OAuthApple.swift
  Project/Projects/OAuth/Apple/TestHost/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Project/Projects/OAuth/Apple/TestHost/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/Projects/OAuth/Apple/TestHost/Resources/Assets.xcassets/Contents.json
  Project/Projects/OAuth/Apple/TestHost/Sources/HostApp.swift
  Project/Projects/OAuth/Apple/Tests/Extension/UIntExtensionTests.swift
  Project/Projects/OAuth/Google/Project.swift
  Project/Projects/OAuth/Google/Resources/Dummy.png
  Project/Projects/OAuth/Google/SampleApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Project/Projects/OAuth/Google/SampleApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/Projects/OAuth/Google/SampleApp/Resources/Assets.xcassets/Contents.json
  Project/Projects/OAuth/Google/SampleApp/Sources/SampleApp.swift
  Project/Projects/OAuth/Google/Sources/Public/OAuthGoogle.swift
  Project/Projects/OAuth/Google/TestHost/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Project/Projects/OAuth/Google/TestHost/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/Projects/OAuth/Google/TestHost/Resources/Assets.xcassets/Contents.json
  Project/Projects/OAuth/Google/TestHost/Sources/HostApp.swift
  Project/Projects/OAuth/Google/Tests/Extension/UIntExtensionTests.swift
  Project/Tools/AboutTime.entitlements
  Project/Tuist/Dependencies.swift
  Project/Tuist/ProjectDescriptionHelpers/Project+App.swift
  Project/Tuist/ProjectDescriptionHelpers/Project+Framework.swift
  Project/Tuist/ProjectDescriptionHelpers/Project+OAuth.swift
  Project/Tuist/ResourceSynthesizers/Json.stencil
  Project/Workspace.swift
Labels: enhancement

#25 Feature/photo picker single
  Project/Projects/Feature/Album/SampleApp/Sources/SampleApp.swift
  Project/Projects/Feature/Album/Sources/Internal/AlbumSingleSelectPhotoView.swift
  Project/Projects/Feature/Album/Sources/Internal/PhotoSelectorFactory.swift
  Project/Projects/Feature/Album/Sources/Internal/SubViews/AlbumListView.swift
  Project/Projects/Feature/Album/Sources/Internal/SubViews/AlbumMultiSelectPhotoView.swift
  Project/Projects/Feature/Album/Sources/Internal/SubViews/AlbumNotPermittedView.swift
  Project/Projects/Feature/Album/Sources/Internal/SubViews/AlbumSingleSelectPhotoView.swift
  Project/Projects/Feature/Album/Sources/Public/AlbumReducer.swift
  Project/Projects/Feature/Album/Sources/Public/AlbumView.swift
  Project/Projects/UIComponents/Resources/Assets/Images.xcassets/_Photo/Contents.json
  Project/Projects/UIComponents/Resources/Assets/Images.xcassets/_Photo/photoExclude.imageset/Contents.json
  Project/Projects/UIComponents/Resources/Assets/Images.xcassets/_Photo/photoExclude.imageset/Exclude.svg
  Project/Projects/UIComponents/Resources/Localization/en.lproj/Localizable.strings
  Project/Projects/UIComponents/Resources/Localization/ko.lproj/Localizable.strings
  Project/Projects/UIComponents/Sources/AutoGenerated/LocalizableMap.swift
  Project/Projects/UIComponents/Sources/Components/ATPHAssetImage.swift
Labels: enhancement

#28 Feature/watch UI
  Project/Projects/ArchiveFoundation/Sources/Model/Meridiem.swift
  Project/Projects/UIComponents/SampleApp/Sources/ContentView.swift
  Project/Projects/UIComponents/Sources/Components/ATWatchTimeSelectorView.swift
Labels: UIComponent
